global:
  # 每5s收集一次数据
  scrape_interval: 5s
  # 每5s执行一次告警规则检测
  evaluation_interval: 5s
  # 标记标签
  external_labels:
    monitor: "monitor"
# 告警配置
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
# 指定规则配置文件
rule_files:
  - rules/*.yml
# 数据抓取配置
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
